run
Gofer new
   gemsource: 'MetacelloRepository';
   package: 'ConfigurationOfPier2';
   load.
MCPlatformSupport commitOnAlmostOutOfMemoryDuring: [
   (Smalltalk at: #ConfigurationOfPier2) project latestVersion load ]

%
run
Gofer new
   gemsource: 'MetacelloRepository';
   package: 'ConfigurationOfPierAddOns2';
   load.
MCPlatformSupport commitOnAlmostOutOfMemoryDuring: [
   (Smalltalk at: #ConfigurationOfPierAddOns2) project latestVersion load: 'Pier-Setup' ]

%
